server:
  port: 8085

spring:
  application:
    name: platform
  cloud:
    nacos:
      config:
        server-addr: nacos-server:8848
        group: xtt-cloud-oa
        file-extension: yaml
      discovery:
        server-addr: nacos-server:8848
        group: xtt-cloud-oa
  config:
    import:
      - optional:nacos:platform.yaml
      - optional:nacos:datasource-config.yaml

  datasource:
    url: jdbc:mysql://mysql:3306/platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xtt.cloud.oa.platform.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: health,info


